### ISSUE TITLE
requests bank 401

### ISSUE THREAD

**Issue by wanggaolin** [pycontribs/python-crowd#39]
app_url = 'http://my.crowd.server:8095/crowd/'
app_user = 'testapp'
app_pass = 'testpass'

where are for this user?

**Comment by aelse** [comment]
Hi, I'm unsure what this question asks, and as it was made a very long time ago you've probably figured it out and moved on. I'm sorry you didn't get a reply at the time. There is very little ongoing maintenance in this project.
